# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e218668e427c4f16a7fd93a78d018ad582722bb9a22aab6f08f679962cabe29e6a5a684358e27a02f6c408093f6dd41f26c686745f57b643e953ef08df8fabc

test:
  secret_key_base: db67c6a719579beea22fff49ea6f7a16a31cafea97d02e28a19bffdc65cc1df992533ef8f393e1b3bafa0a050a5be99a48c1cc8a84765efb5f306c24b7a0f0ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
